// <auto-generated />
using System;
using CareerHub_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareerHub_API.Migrations
{
    [DbContext(typeof(CareerHubDbContext))]
    partial class CareerHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CareerHub_API.Models.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("applicants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Email = "john@example.com",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            Email = "sarah@example.com",
                            Name = "Sarah Lee"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-333333333333"),
                            Email = "michael@example.com",
                            Name = "Michael Smith"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-444444444444"),
                            Email = "aisha@example.com",
                            Name = "Aisha Khan"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-5555-5555-5555-eeeeeeeeeeee"),
                            Email = "david@example.com",
                            Name = "David Brown"
                        });
                });

            modelBuilder.Entity("CareerHub_API.Models.Application", b =>
                {
                    b.Property<Guid>("JobListingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("JobListingId", "ApplicantId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("applications", (string)null);

                    b.HasData(
                        new
                        {
                            JobListingId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ApplicantId = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Status = 0,
                            SubmittedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            JobListingId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ApplicantId = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            Status = 1,
                            SubmittedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            JobListingId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ApplicantId = new Guid("cccccccc-3333-3333-3333-333333333333"),
                            Status = 2,
                            SubmittedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            JobListingId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ApplicantId = new Guid("dddddddd-4444-4444-4444-444444444444"),
                            Status = 3,
                            SubmittedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            JobListingId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ApplicantId = new Guid("eeeeeeee-5555-5555-5555-eeeeeeeeeeee"),
                            Status = 4,
                            SubmittedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CareerHub_API.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Industry = "Software",
                            Name = "TechNova",
                            Website = "https://technova.com"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Industry = "Finance",
                            Name = "FinCore",
                            Website = "https://fincore.com"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Industry = "Healthcare",
                            Name = "HealthPlus",
                            Website = "https://healthplus.com"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Industry = "Education",
                            Name = "EduSmart",
                            Website = "https://edusmart.com"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Industry = "Energy",
                            Name = "GreenEnergy",
                            Website = "https://greenenergy.com"
                        });
                });

            modelBuilder.Entity("CareerHub_API.Models.JobListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Title");

                    b.ToTable("job_listings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Build APIs with .NET",
                            Location = "Remote",
                            PostedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Backend Developer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CompanyId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Description = "Analyse financial data",
                            Location = "Johannesburg",
                            PostedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Financial Analyst"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CompanyId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Description = "Patient care and support",
                            Location = "Cape Town",
                            PostedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Nurse Specialist"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CompanyId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Description = "Teach computer science",
                            Location = "Pretoria",
                            PostedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Lecturer"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CompanyId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Description = "Renewable energy systems",
                            Location = "Durban",
                            PostedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Energy Engineer"
                        });
                });

            modelBuilder.Entity("CareerHub_API.Models.Application", b =>
                {
                    b.HasOne("CareerHub_API.Models.Applicant", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerHub_API.Models.JobListing", "JobListing")
                        .WithMany("Applications")
                        .HasForeignKey("JobListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("JobListing");
                });

            modelBuilder.Entity("CareerHub_API.Models.JobListing", b =>
                {
                    b.HasOne("CareerHub_API.Models.Company", "Company")
                        .WithMany("JobListings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CareerHub_API.Models.Applicant", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("CareerHub_API.Models.Company", b =>
                {
                    b.Navigation("JobListings");
                });

            modelBuilder.Entity("CareerHub_API.Models.JobListing", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
